#ifndef SYRIAL_BOOTKIT_DEFS_H
#define SYRIAL_BOOTKIT_DEFS_H

#define KERNEL_PAYLOAD_ADDRESS 0x400000  

extern EFI_BOOT_SERVICES* gBS;
extern EFI_SYSTEM_TABLE* gST;
extern EFI_RUNTIME_SERVICES* gRT;

#endif
