In code:
"using System;
using System.Net.Http;
using System.Threading.Tasks;

class SyrialHelper
{
    static async Task Main()
    {
        HttpClient client = new HttpClient();
        var response = await client.GetAsync("http://localhost:3000/keys"); //fucking example
        string json = await response.Content.ReadAsStringAsync();
        Console.WriteLine("Fetched current keys:\n" + json);
    }
}"
